# Generated by Django 3.0.7 on 2020-06-11 09:02

from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('url', models.URLField(blank=True, null=True)),
                ('image', stdimage.models.JPEGField(upload_to='client')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
