# Generated by Django 3.0.7 on 2020-06-17 11:10

from django.db import migrations, models
import django.db.models.deletion
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tag', '0001_initial'),
        ('technology', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('jobtitle', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', stdimage.models.JPEGField(upload_to='employee')),
                ('tags', models.ManyToManyField(to='tag.Tag')),
            ],
            options={
                'ordering': ['firstname', 'lastname'],
            },
        ),
        migrations.CreateModel(
            name='TechnologyLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.SmallIntegerField(choices=[(None, '(Unknown)'), (1, 'Beginner'), (3, 'Intermediate'), (5, 'Advanced')])),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.Employee')),
                ('technology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='technology.Technology')),
            ],
            options={
                'ordering': ['-level', 'technology__name'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField()),
                ('company', models.CharField(max_length=100)),
                ('job_title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='employee.Employee')),
            ],
            options={
                'ordering': ['-start'],
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='technologies',
            field=models.ManyToManyField(through='employee.TechnologyLevel', to='technology.Technology'),
        ),
    ]
