# Generated by Django 3.0.7 on 2020-06-17 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
    ]
