# Generated by Django 3.0.7 on 2020-06-16 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technologylevel',
            name='level',
            field=models.SmallIntegerField(choices=[(None, '(Unknown)'), (1, 'Beginner'), (3, 'Intermediate'), (5, 'Advanced')]),
        ),
    ]
