# Generated by Django 3.0.7 on 2020-06-16 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='start',
            field=models.DateField(),
        ),
    ]
