# Generated by Django 3.0.7 on 2020-06-23 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_auto_20200618_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='teaser',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
