# Generated by Django 3.0.7 on 2020-07-02 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technology', '0001_initial'),
        ('employee', '0005_auto_20200702_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='technologies',
            field=models.ManyToManyField(related_name='consultants', through='employee.TechnologyLevel', to='technology.Technology'),
        ),
    ]
