# Generated by Django 3.0.7 on 2020-07-06 12:25

from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('image', stdimage.models.JPEGField(upload_to='service_area/')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
