# Generated by Django 3.0.7 on 2020-07-06 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0002_servicearea'),
        ('project', '0002_auto_20200702_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='service_area',
            field=models.ManyToManyField(related_name='service_projects', to='tag.ServiceArea'),
        ),
    ]
