# Generated by Django 3.0.7 on 2020-07-10 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technology', '0003_auto_20200710_1031'),
        ('project', '0004_auto_20200710_1030'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='service_area',
            new_name='service_areas',
        ),
        migrations.AlterField(
            model_name='project',
            name='technologies',
            field=models.ManyToManyField(related_name='projects', to='technology.Technology'),
        ),
    ]
