# Generated by Django 3.0.7 on 2020-07-10 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0002_servicearea'),
        ('technology', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='technology',
            name='service_area',
            field=models.ManyToManyField(related_name='technologies', to='tag.ServiceArea'),
        ),
    ]
