# Generated by Django 3.0.7 on 2020-07-10 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('technology', '0002_technology_service_area'),
    ]

    operations = [
        migrations.RenameField(
            model_name='technology',
            old_name='service_area',
            new_name='service_areas',
        ),
    ]
